services:
  db:
    container_name: db
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: news
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '3306:3306'
    networks:
      - guacu-news-scrapping-net
    volumes:
      - '/docker/db/data:/var/lib/mysql'
      - '/docker/db/my.cnf:/etc/mysql/conf.d/my.cnf'
      - './docker/db/sql:/docker-entrypoint-initdb.d'
  app:
    container_name: guacu_news_scrapping
    build: .
    depends_on:
      - db
    networks:
      - guacu-news-scrapping-net
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - guacu-news-scrapping-net
networks:
  guacu-news-scrapping-net:
    driver: bridge
