CREATE DATABASE IF NOT EXISTS news;
USE news;

CREATE TABLE IF NOT EXISTS news (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(512) NOT NULL,
  link VARCHAR(512) NOT NULL,
  posted_at VARCHAR(255) NOT NULL,
  source VARCHAR(128) NOT NULL DEFAULT '',
  city VARCHAR(128) NOT NULL DEFAULT '',
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      published TINYINT(1) NOT NULL DEFAULT 0,
      UNIQUE KEY uq_news_link (link)
);
